var boardsList = [
		{"abbr":"abu","name":"Aбу","group":"Разное"},
		{"abbr":"b","name":"Бред","group":"Разное"},
		{"abbr":"d","name":"Обсуждение двача","group":"Разное"}, 
		{"abbr":"fag","name":"Фагготрия","group":"Разное"},
		{"abbr":"soc","name":"Общение","group":"Разное"},
		{"abbr":"r","name":"Просьбы","group":"Разное"},
		{"abbr":"int","name":"International","group":"Разное"},
		{"abbr":"app","name":"Мобильные приложения","group":"Тематика"},
		{"abbr":"au","name":"Автомобили и транспорт","group":"Тематика"},
		{"abbr":"bi","name":"Велосипеды","group":"Тематика"},
		{"abbr":"biz","name":"Бизнес","group":"Тематика"},
		{"abbr":"bo","name":"Книги","group":"Тематика"},
		{"abbr":"c","name":"Комиксы и мультфильмы","group":"Тематика"},
		{"abbr":"di","name":"Столовая","group":"Тематика"},
		{"abbr":"em","name":"Другие страны и туризм","group":"Тематика"},
		{"abbr":"ew","name":"Конец света","group":"Тематика"},
		{"abbr":"fa","name":"Мода и стиль","group":"Тематика"},
		{"abbr":"fiz","name":"Физкультура","group":"Тематика"},
		{"abbr":"fl","name":"Иностранные языки","group":"Тематика"},
		{"abbr":"ftb","name":"Футбол","group":"Тематика"},
		{"abbr":"gd","name":"Gamedev","group":"Тематика"},
		{"abbr":"hh","name":"Хип-хоп культура","group":"Тематика"},
		{"abbr":"hi","name":"История","group":"Тематика"},
		{"abbr":"hw","name":"Железо","group":"Тематика"},
		{"abbr":"me","name":"Медицина","group":"Тематика"},
		{"abbr":"mg","name":"Магия","group":"Тематика"},
		{"abbr":"mlp","name":"My little pony","group":"Тематика"},
		{"abbr":"mov","name":"Фильмы","group":"Тематика"},
		{"abbr":"mo","name":"Мотоциклы","group":"Тематика"},
		{"abbr":"mu","name":"Музыка","group":"Тематика"},
		{"abbr":"ne","name":"Животные и природа","group":"Тематика"},
		{"abbr":"pvc","name":"Коллекционные фигурки","group":"Тематика"},
		{"abbr":"po","name":"Политика и новости","group":"Тематика"},
		{"abbr":"pr","name":"Программирование","group":"Тематика"},
		{"abbr":"psy","name":"Психология","group":"Тематика"},
		{"abbr":"ra","name":"Радиотехника","group":"Тематика"},
		{"abbr":"re","name":"Религия и философия","group":"Тематика"},
		{"abbr":"s","name":"Программы","group":"Тематика"},
		{"abbr":"sf","name":"Научная фантастика","group":"Тематика"},
		{"abbr":"sci","name":"Наука","group":"Тематика"},
		{"abbr":"sn","name":"Паранормальные явления","group":"Тематика"},
		{"abbr":"sp","name":"Спорт","group":"Тематика"},
		{"abbr":"spc","name":"Космос","group":"Тематика"},
		{"abbr":"t","name":"Техника","group":"Тематика"},
		{"abbr":"tr","name":"Транспорт и авиация","group":"Тематика"},
		{"abbr":"tv","name":"Тв","group":"Тематика"},
		{"abbr":"un","name":"Образование","group":"Тематика"},
		{"abbr":"wh","name":"Warhammer","group":"Тематика"},
		{"abbr":"wm","name":"Военная техника","group":"Тематика"},
		{"abbr":"w","name":"Оружие","group":"Тематика"},
		{"abbr":"de","name":"Дизайн","group":"Хобби"},
		{"abbr":"diy","name":"Хобби","group":"Хобби"},
		{"abbr":"dom","name":"Домострой","group":"Хобби"},
		{"abbr":"f","name":"Flash &amp","name":"gif","group":"Хобби"},
		{"abbr":"izd","name":"Издательство","group":"Хобби"},
		{"abbr":"mus","name":"Музыканты","group":"Хобби"},
		{"abbr":"o","name":"Мазня","group":"Хобби"},
		{"abbr":"pa","name":":Живопись","group":"Хобби"},
		{"abbr":"p","name":"Фото","group":"Хобби"},
		{"abbr":"wp","name":"Обои и высокое разрешение","group":"Хобби"},
		{"abbr":"td","name":"Трёхмерная графика","group":"Хобби"},
		{"abbr":"bg","name":"Настольные игры","group":"Игры"},
		{"abbr":"cg","name":"Консоли","group":"Игры"},
		{"abbr":"gb","name":"Азартные игры","group":"Игры"},
		{"abbr":"mc","name":"Minecraft","group":"Игры"},
		{"abbr":"mmo","name":"MMO","group":"Игры"},
		{"abbr":"vg","name":"Видеоигры","group":"Игры"},
		{"abbr":"wr","name":"Текстовые ролевые игры","group":"Игры"},
		{"abbr":"tes","name":"The elder scrolls","group":"Игры"},
		{"abbr":"a","name":"Аниме","group":"Япония"},
		{"abbr":"aa","name":"Аниме арт","group":"Япония"},
		{"abbr":"fd","name":"Фэндом","group":"Япония"},
		{"abbr":"ja","name":"Япония","group":"Япония"},
		{"abbr":"ma","name":"Манга","group":"Япония"},
		{"abbr":"rm","name":"Rozen Maiden","group":"Япония"},
		{"abbr":"to","name":"Touhou","group":"Япония"},
		{"abbr":"vn","name":"Визуальные новеллы","group":"Япония"}
];